'use client';

import { Inter } from "next/font/google";
import {Header} from "@/layout/Header";
import s from './layout.module.scss';
import {Content} from "@/layout/Content";
import {Navigation} from "@/layout/Navigation";
import {Sidebar} from "@/layout/Sidebar";
import {Footer} from "@/layout/Footer";
import {AltroneApplication} from "altrone-ui";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<div className={s.Layout}>
    <Navigation />
    <Content>
      {children}
    </Content>
    <Sidebar />
  </div>);
}
